require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AmmenitiesController do

  # This should return the minimal set of attributes required to create a valid
  # Ammenity. As you add validations to Ammenity, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all ammenities as @ammenities" do
      ammenity = Ammenity.create! valid_attributes
      get :index
      assigns(:ammenities).should eq([ammenity])
    end
  end

  describe "GET show" do
    it "assigns the requested ammenity as @ammenity" do
      ammenity = Ammenity.create! valid_attributes
      get :show, :id => ammenity.id
      assigns(:ammenity).should eq(ammenity)
    end
  end

  describe "GET new" do
    it "assigns a new ammenity as @ammenity" do
      get :new
      assigns(:ammenity).should be_a_new(Ammenity)
    end
  end

  describe "GET edit" do
    it "assigns the requested ammenity as @ammenity" do
      ammenity = Ammenity.create! valid_attributes
      get :edit, :id => ammenity.id
      assigns(:ammenity).should eq(ammenity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ammenity" do
        expect {
          post :create, :ammenity => valid_attributes
        }.to change(Ammenity, :count).by(1)
      end

      it "assigns a newly created ammenity as @ammenity" do
        post :create, :ammenity => valid_attributes
        assigns(:ammenity).should be_a(Ammenity)
        assigns(:ammenity).should be_persisted
      end

      it "redirects to the created ammenity" do
        post :create, :ammenity => valid_attributes
        response.should redirect_to(Ammenity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ammenity as @ammenity" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ammenity.any_instance.stub(:save).and_return(false)
        post :create, :ammenity => {}
        assigns(:ammenity).should be_a_new(Ammenity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ammenity.any_instance.stub(:save).and_return(false)
        post :create, :ammenity => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ammenity" do
        ammenity = Ammenity.create! valid_attributes
        # Assuming there are no other ammenities in the database, this
        # specifies that the Ammenity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ammenity.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => ammenity.id, :ammenity => {'these' => 'params'}
      end

      it "assigns the requested ammenity as @ammenity" do
        ammenity = Ammenity.create! valid_attributes
        put :update, :id => ammenity.id, :ammenity => valid_attributes
        assigns(:ammenity).should eq(ammenity)
      end

      it "redirects to the ammenity" do
        ammenity = Ammenity.create! valid_attributes
        put :update, :id => ammenity.id, :ammenity => valid_attributes
        response.should redirect_to(ammenity)
      end
    end

    describe "with invalid params" do
      it "assigns the ammenity as @ammenity" do
        ammenity = Ammenity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ammenity.any_instance.stub(:save).and_return(false)
        put :update, :id => ammenity.id, :ammenity => {}
        assigns(:ammenity).should eq(ammenity)
      end

      it "re-renders the 'edit' template" do
        ammenity = Ammenity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ammenity.any_instance.stub(:save).and_return(false)
        put :update, :id => ammenity.id, :ammenity => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ammenity" do
      ammenity = Ammenity.create! valid_attributes
      expect {
        delete :destroy, :id => ammenity.id
      }.to change(Ammenity, :count).by(-1)
    end

    it "redirects to the ammenities list" do
      ammenity = Ammenity.create! valid_attributes
      delete :destroy, :id => ammenity.id
      response.should redirect_to(ammenities_url)
    end
  end

end
